# Generated by Django 2.1.5 on 2024-02-23 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSearchTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200)),
                ('overall', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('usefulness', models.IntegerField()),
                ('workload', models.IntegerField()),
                ('reviews', models.IntegerField()),
                ('wouldRecommend', models.FloatField()),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturer.Course')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackTime', models.DateTimeField(auto_now_add=True)),
                ('friendly', models.IntegerField()),
                ('overall', models.IntegerField()),
                ('aesthetic', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
