# Generated by Django 2.1.5 on 2024-02-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyUogCourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesearchtable',
            name='professorRating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
