# Generated by Django 2.1.5 on 2024-03-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyUogCourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitefeedback',
            name='id',
        ),
        migrations.AddField(
            model_name='websitefeedback',
            name='feedbackId',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='websitefeedback',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
